# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.cache/wt} [current_project]
set_property parent.project_path {D:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.srcs/sources_1/new/Registers.vhd}
  {D:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.srcs/sources_1/new/ALU.vhd}
  {D:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.srcs/sources_1/new/PC.vhd}
  {D:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.srcs/sources_1/new/MPC.vhd}
  {D:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.srcs/sources_1/new/Microcode_Unit.vhd}
  {D:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.srcs/sources_1/new/Data_memory.vhd}
  {D:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.srcs/sources_1/new/MPG.vhd}
  {D:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.srcs/sources_1/new/Instruction_memory.vhd}
  {D:/Facultate/ANUL 3/ANUL 3 - Semestrul 1/SSC/Proiect/Proiect_EMMA_2/Proiect_EMMA_2.srcs/sources_1/new/Emma_2.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Emma_2 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Emma_2.dcp

catch { report_utilization -file Emma_2_utilization_synth.rpt -pb Emma_2_utilization_synth.pb }
